Adopt build system to run on legacy i686 system
Use Makefile instead of CMake - the latter did not successfully run,
whereas Makefile run out of the box.
CMake giving this error message (namespace issue with std::experimental?):

Scanning dependencies of target treesheets
[  6%] Building CXX object CMakeFiles/treesheets.dir/lobster/src/builtins.cpp.o
In file included from /home/martin/Projects/treesheets/lobster/src/lobster/stdafx.h:91:0,
                 from /home/martin/Projects/treesheets/lobster/src/builtins.cpp:15:
/home/martin/Projects/treesheets/lobster/src/lobster/tools.h:724:19: error: ‘FNV1A’ declared as an ‘inline’ variable
 inline uint FNV1A(string_view s) {
                   ^
/home/martin/Projects/treesheets/lobster/src/lobster/tools.h:724:19: error: ‘string_view’ was not declared in this scope
/home/martin/Projects/treesheets/lobster/src/lobster/tools.h:724:19: note: suggested alternative:
In file included from /home/martin/Projects/treesheets/lobster/src/lobster/stdafx.h:62:0,
                 from /home/martin/Projects/treesheets/lobster/src/builtins.cpp:15:
/usr/include/c++/4.9/experimental/string_view:574:46: note:   ‘std::experimental::string_view’
   using string_view = basic_string_view<char>;
                                              ^
In file included from /home/martin/Projects/treesheets/lobster/src/lobster/stdafx.h:91:0,
                 from /home/martin/Projects/treesheets/lobster/src/builtins.cpp:15:
/home/martin/Projects/treesheets/lobster/src/lobster/tools.h:724:34: error: expected ‘,’ or ‘;’ before ‘{’ token
 inline uint FNV1A(string_view s) {
                                  ^
make[2]: *** [CMakeFiles/treesheets.dir/lobster/src/builtins.cpp.o] Error 1
make[1]: *** [CMakeFiles/treesheets.dir/all] Error 2
make: *** [all] Error 2